- Cargo.lock
- Cargo.toml
- agents/processor/Cargo.toml
- chains/nomad-ethereum/src/bindings/home.rs
- chains/nomad-ethereum/src/bindings/replica.rs
- chains/nomad-ethereum/src/bindings/xappconnectionmanager.rs
- configuration/Cargo.toml
- nomad-types/Cargo.toml
- tools/balance-exporter/Cargo.toml
- tools/balance-exporter/src/main.rs
- tools/kms-cli/Cargo.toml
- tools/kms-cli/src/main.rs
updates balance exporter and kms cli to use a non-beta version of clap
> chore: update clap in CLI

- agents/relayer/src/relayer.rs
- agents/watcher/src/watcher.rs
- nomad-base/src/agent.rs
- nomad-base/src/contract_sync/mod.rs
- nomad-base/src/metrics.rs
- nomad-base/src/settings/mod.rs
- straight `IntGauge` not showing up in Grafana so switch to use `IntGaugeVec`
- key watcher `IntGaugeVec` by useful contract keys
> fix: use IntGaugeVec for watcher and home fail metrics and key by correct contracts

- configuration/CHANGELOG.md
- configuration/src/lib.rs
Wasm bindings can't parse returning Option. Fixes add_domain to return Result.
> fix: add_domain returns result for wasm bindings

- chains/nomad-ethereum/src/home.rs
- chains/nomad-ethereum/src/replica.rs
- want to avoid calling `eth_estimateGas` due to constant RPC problems
- using past estimates from indexer dataset, we've 2xed avg gas limits for all non-fraud related contract methods
> fix: hardcode non-fraud methods to 2x avg gas limit

- chains/nomad-ethereum/src/home.rs
- chains/nomad-ethereum/src/replica.rs
- nomad-base/src/home.rs
- nomad-core/src/traits/home.rs
- nomad-test/src/mocks/home.rs
**Will go in docs repo:**
```
Update (replica), 
- 70k on average
- Double that to 140k (constant)
Prove
- 100k on average
- Double that to 200k (constant since merkle proofs always same size)
Update (home)
- Take average limit for one message (50k) and double base to 100k
- Each additional message dequeued is ~5k gas so double that cost to 10k per message
- 100k + (num_messages * 10k)
Process
- Minimum 850k required
- Double minimum 1.7M
ProveAndProcess
- 1.7M for process
- 200k for prove
- 1.9M total
```
> fix: account for update gas variability and adjust gas limits

- Cargo.lock
- agents/updater/src/submit.rs
- agents/updater/src/updater.rs
- chains/nomad-ethereum/src/home.rs
- chains/nomad-ethereum/src/lib.rs
- chains/nomad-ethereum/src/macros.rs
- chains/nomad-ethereum/src/replica.rs
- chains/nomad-ethereum/src/xapp.rs
- nomad-base/src/home.rs
- nomad-base/src/replica.rs
- nomad-base/src/settings/chains.rs
- nomad-base/src/settings/mod.rs
- nomad-base/src/xapp.rs
- tools/nomad-cli/src/subcommands/prove.rs
- ethers-rs #100 bump fixed updater timelag but did broke tx submission due to fetching timelagged nonces
- PR creates two separate providers for reads and writes for contract objects
- Also bumps ethers again to re-include the timelag fix which originally caused the timelag x nonce bug
- Removes timelag usage for replicas, as we only need it for updater safety on home and processor indexing of `Dispatch` events
> refactor/fix: contract objects take two separate providers for reads and writes

- agents/kathy/src/main.rs
- agents/processor/src/main.rs
- agents/relayer/src/main.rs
- agents/updater/src/main.rs
- agents/watcher/src/main.rs
- tools/kms-cli/src/main.rs
`#[tokio::main(flavor = "current_thread")]`
expands to the same runtime setup
```rust
tokio::runtime::Builder::new_current_thread()
.enable_all()
.build()
.unwrap()
.block_on(body)
```
> style: use tokio::main macro

- configuration/configs/production.json
We should only have networks we want to show in the GUI
> fix: remove xdai from gui config

- Cargo.lock
- configuration/CHANGELOG.md
- configuration/Cargo.toml
- configuration/data/types.rs
Enable connext for evmos in the production gui
Release configuration package with the flag connextEnabled turned on for evmos in production so gui/sk packages can use
> chore: bump configuration package and update changelog

- Cargo.lock
- agents/processor/src/processor.rs
- configuration/CHANGELOG.md
- configuration/configs/development.json
- configuration/configs/production.json
- configuration/configs/staging.json
- configuration/data/definitions.ts
- configuration/data/types.rs
- configuration/src/agent/processor.rs
- configuration/src/lib.rs
- configuration/src/wasm/types.rs
- nomad-base/src/settings/macros.rs
s3 info is currently deeply nested in the config, and not available to TS.
- duplicate s3 config at top level
> Move s3 to top-level of config 

- accumulator/src/lib.rs
- configuration/CHANGELOG.md
- nomad-core/src/test_output.rs
Tests behind the feature flag `output` are broken and not picked up by CI due to relaxed testing. This needs to get fixed before CI can be updated to catch all features.
Ref https://github.com/nomad-xyz/rust/issues/118
Fix the broken tests.
> fix: failing output tests

- .github/workflows/rust.yml
The `cargo test` command was relaxed when being ported to the workflow from the original monorepo, causing tests behind feature flags to be skipped.
Ref https://github.com/nomad-xyz/rust/issues/118
NOTE:
**Requires https://github.com/nomad-xyz/rust/pull/165 to be pushed first or all tests will start failing**
Make the `cargo test` and `fmt`, `clippy` and `build` commands more explicit
> chore: update workflow

- configuration/src/gas/mod.rs
- configuration/src/lib.rs
The `NomadGasConfigs` exists only for deserialization convenience. We should prevent it from being in public-facing types
Use `deserialize_with` and a crate-scoped module
- [n/a] Updated CHANGELOG.md for the appropriate package
> refactor: prevent convenience type from leaking into non-ser code

- Cargo.lock
- configuration/CHANGELOG.md
- configuration/Cargo.toml
- configuration/configs/staging.json
goerli staging url string typo
fix the typo
> fix: typo in goerli rpc url

- agents/updater/src/updater.rs
Updater currently crashes all the time when txs error out instead of handling gracefully like processor and relayer.
Apply channel/run_report_err pattern (same as relayer and processor) to updater. Updater now spawns one task for producing and submitting updates using `self.run_report_err(...)`. If tx submission errors out, that will be caught and retried with exponential backoff.
> refactor(updater): updater gracefully handles errors

- provision_kms_keys.py
Fixed KMS key provisioner to support over 100 aliases. This tool should be refactored and moved to a different repository.
Could not provision new keys since we have over 100 aliases in our AWS account
Added support for fetching over 100 aliases from AWS KMS
> Fixed AWS KMS provisioner tool to fetch over 100 aliases

- Cargo.lock
- configuration/CHANGELOG.md
- configuration/Cargo.toml
- configuration/configs/production.json
Don't show gnosis in prod gui just yet
Remove gnosis from the bridgeGUI section
> Remove gnosis chain from prod gui

- agents/processor/CHANGELOG.md
- agents/processor/src/processor.rs
- chains/nomad-ethereum/src/macros.rs
- nomad-base/CHANGELOG.md
- nomad-base/src/nomad_db.rs
- nomad-core/CHANGELOG.md
- nomad-core/src/traits/encode.rs
Next version of replica will allow processing to fail, reverting the tx entirely. The process currently cannot handle that. There are two problems
1. The processor will error if the `process` call errors
2. The processor will re-attempt errored `process` calls on next reboot 
- Store a bool in the DB when the processor attempts to prove/process a message
- Do not re-attempt messages that were previously attempted
- Do not error if process transactions error
- Enhanced logging for the prove/process flow
This prevents the processor from erroring on failed `process` calls. It also ensures that a failed call will not be re-attempted
cc @anna-carroll for visibility
> Disable process retry

- agents/processor/src/processor.rs
- chains/nomad-ethereum/abis/Replica.abi.json
- chains/nomad-ethereum/src/bindings/replica.rs
- chains/nomad-ethereum/src/replica.rs
- nomad-core/src/traits/replica.rs
- tools/nomad-cli/src/subcommands/prove.rs
We failed to consider interaction of backwards compatible contract type changes with the agents' rust type system
Update abi bindings with new message status system
disable double-updates by returning an empty txoutcome
> fix: update agent ABI and remove double-update

- configuration/build.rs
For now, we don't have `config` repo CI. Want to manual validate by pasting config from `config` into rust repo and checking tests.
Optional ability to disable fetching configs in build so that we don't always load gh pages configs on `cargo test`. We can now disable build, paste in new config we want to validate, and run test with `BUILD_DISABLED=true cargo test`
> feat(configuration): optionally disable build

- configuration/CHANGELOG.md
- configuration/src/gas/defaults.rs
Gas estimate hardcodes generally a bit high. Causes extremely high estimates for devnets due to high number of messages being constantly enqueued.
Remove evmDefault hardcodes where not necessary (only needed on Moonbeam, Milkomeda, and xDai given past history). Also lower per-message gas hardcode for home:update.
> fix(config): lower per-message gas hardcode

- agents/processor/CHANGELOG.md
- agents/processor/src/processor.rs
- nomad-base/CHANGELOG.md
- nomad-base/src/agent.rs
Processor was encountering a panic when running with only an ethereum remote
```
Message:  assertion failed: !ret.inner.is_empty()
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/select_all.rs:40
```
- the error occurs because `futures_util::select_all` is invoked with an empty vector. 
- the only place where this could occur **in our code** is in `NomadAgent::run_many` which calls `select_all` on the result of an iterator
- `grep -ri --include="*.rs" "select_all" *` will identify locations where `select_all` is invoked
- this iterator may only be empty if the names slice is empty when called
- `NomadAgent::run_many` is invoked from `NomadAgent::run_all`
- it is also invoked from `<Processor as **NomadAgent>::run_all` overriding the …
> fix: prevent processor from attempting to run an empty select_all

- agents/relayer/CHANGELOG.md
- agents/relayer/src/relayer.rs
Only way we're noticing updater addresses are misconfigured is through `!updater sig` revert. Want to check this in relayer instead.
Relayer checks updater addresses match when starting a home<>replica task.
> feat(relayer): add check for replica updater addresses

- Cargo.lock
- agents/kathy/CHANGELOG.md
- agents/kathy/src/main.rs
- agents/kathy/src/settings.rs
- agents/processor/CHANGELOG.md
- agents/processor/src/main.rs
- agents/processor/src/settings.rs
- agents/relayer/CHANGELOG.md
- agents/relayer/src/main.rs
- agents/relayer/src/settings.rs
- agents/updater/CHANGELOG.md
- agents/updater/src/main.rs
- agents/updater/src/settings.rs
- agents/watcher/CHANGELOG.md
- agents/watcher/src/main.rs
- agents/watcher/src/settings.rs
- configuration/CHANGELOG.md
- nomad-base/CHANGELOG.md
- nomad-base/src/settings/macros.rs
- nomad-test/CHANGELOG.md
- nomad-test/Cargo.toml
- nomad-test/src/test_utils.rs
Currently changing agent config requires updating a central config repo & rebuilding docker images. For debugging and testing, being able to override an agent's config at runtime will add speed & flexibility. 
Supports https://github.com/nomad-xyz/rust/issues/216
Add support for a `CONFIG_URL` env var, which will take precedence over `CONFIG_PATH` and `RUN_ENV` and update config handling to support fetching a remote config.
> feat(configuration): make config url overridable via env var

- .github/pull_request_template.md
- agents/relayer/src/relayer.rs
- agents/watcher/src/watcher.rs
- nomad-base/CHANGELOG.md
- nomad-base/src/contract_sync/metrics.rs
- nomad-base/src/contract_sync/mod.rs
- nomad-base/src/settings/mod.rs
Need clearer metrics on indexing updates (is it an update or is it a relayed update event?).
ContractSync take `home` and `replica` labels. If agent is indexing home, both labels will be same network.
> fix(metrics): contract sync metrics take home and replica labels

- Cargo.lock
- agents/kathy/src/settings.rs
- chains/nomad-ethereum/src/gelato.rs
updates gelato-sdk to latest `main`
get recent enhanced logging for abnormal RPC responses
- `cargo update -p gelato-sdk`
- delete expect on method that no longer returns an option
- driveby lint
> chore: update gelato sdk and resolve compilation issue

- configuration/CHANGELOG.md
- configuration/configs/test.json
- configuration/data/definitions.ts
- configuration/src/agent/processor.rs
- configuration/src/bridge.rs
- configuration/src/network.rs
- configuration/src/wasm/types.rs
- nomad-base/CHANGELOG.md
- nomad-base/src/metrics.rs
As of 1.1.0, the protcol is no longer gas-aware. We have removed these keys from the deployment process, and should remove them from the config types
- Remove protocol gas configuration keys from the configuration types
- Remove them from wasm typedefs as well
- delete these keys from env configs in main config repo
> refactor: remove deprecated deploy configuration keys

- agents/processor/CHANGELOG.md
- agents/processor/src/processor.rs
- agents/relayer/CHANGELOG.md
- agents/relayer/src/relayer.rs
- agents/watcher/CHANGELOG.md
- agents/watcher/src/watcher.rs
- chains/nomad-ethereum/CHANGELOG.md
- chains/nomad-ethereum/src/home.rs
- chains/nomad-ethereum/src/replica.rs
- nomad-base/CHANGELOG.md
- nomad-base/src/home.rs
- nomad-base/src/replica.rs
- nomad-core/CHANGELOG.md
- nomad-core/src/traits/mod.rs
- nomad-test/CHANGELOG.md
- nomad-test/src/mocks/home.rs
- nomad-test/src/mocks/replica.rs
Because the contracts don't implement display, we used debug for them. This was a bad idea
- require `Common` inheritors to implement `Display`
- use `Display` when emitting events
> fix: prevent some gigantic log lines by adding better display impls

- Cargo.lock
- configuration/CHANGELOG.md
- configuration/Cargo.toml
Substrate compatible agents and deploy script.
#233 integrated substrate into `configuration` crate, this PR prepares new RC.
> Bump `configuration` version to 1.0.0 after adding substrate to config

- configuration/CHANGELOG.md
- configuration/src/agent/signer.rs
Recent changes to Watcher to make it more verbose in logging incorrectly included the secrets contained in `SignerConf`
Rather than remove the offending logging from Watcher, prevent `SignerConf` from printing `Debug` or `Display` that includes secrets to ensure this mistake is not repeated in the future
> fix(configuration): prevent SignerConf from being logged with secrets

- agents/kathy/CHANGELOG.md
- agents/kathy/src/kathy.rs
- agents/processor/CHANGELOG.md
- agents/processor/src/processor.rs
- agents/processor/src/prover_sync.rs
- agents/processor/src/push.rs
- agents/relayer/CHANGELOG.md
- agents/relayer/src/relayer.rs
- agents/updater/CHANGELOG.md
- agents/updater/src/produce.rs
- agents/updater/src/submit.rs
- agents/updater/src/updater.rs
- agents/watcher/CHANGELOG.md
- agents/watcher/src/watcher.rs
- nomad-base/CHANGELOG.md
- nomad-base/src/agent.rs
- nomad-base/src/contract_sync/mod.rs
- nomad-base/src/home.rs
- nomad-base/src/macros.rs
- nomad-base/src/replica.rs
A misunderstanding of the tracing/futures interaction caused many span we were creating to be improperly suppressed
Apply the spans to the futures, not the join handles wrapping tasks containing those futures
@yourbuddyconner @arnaud036 this will enable many spans that were previously accidentally suppressed, causing log output to be more significantly more detailed and verbose. It may require some tuning if it's toooo verbose
@luketchang @lattejed dear reviewers, this PR is not as big as it seems. the move from `}).instrument()` to `}.instrument())` caused an extra indentation for affected blocks, and in some cases re-formatting on the rustfmt run. The changes are closer to 30 lines than 300 😅 
- [] Ran PR in local/dev/staging
> fix: instrument futures, not joinhandles
