nomad-xyz/rust

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml, configuration/src/lib.rs
Based on https://github.com/nomad-xyz/monorepo/issues/107#issuecomment-1084811839
=> fix: removed validation after domain added

Cargo.lock, tools/kms-cli/src/main.rs, tools/nomad-cli/src/subcommands/prove.rs
Include this: https://github.com/gakonst/ethers-rs/pull/1099/files
=> fix: bump ethers to include aws fix

configuration/CHANGELOG.md, configuration/configs/development.json, configuration/configs/production.json, configuration/configs/staging.json, configuration/data/definitions.ts, configuration/data/types.rs, configuration/src/wasm/types.rs
Add config data for `bridgeGui`
Add `chainId` field to `AppConfig`
=> add: gui configs

configuration/configs/production.json
- left out agent and bridgeGui config info
- putting them back :(
=> fix(config): add xdai agent and gui configs

Cargo.lock
=> chore: update ethers to latest master and relock

Cargo.lock
This reverts commit 2dd76cded2363f27b4beca113940913161801b44.
=> revert: "chore: update ethers to latest master and relock (#100)"

configuration/CHANGELOG.md, configuration/configs/development.json, configuration/configs/production.json, configuration/data/definitions.ts, configuration/src/bridge.rs, configuration/src/wasm/types.rs
Related (https://github.com/nomad-xyz/nomad-app/issues/255)
Will make a lot of `config.dev.ts` and `config.main.ts` irrelevant which we can then remove from the gui ✨ (https://github.com/nomad-xyz/nomad-app/tree/development/src/config)
=> feat: add bridge gui specific configs, update types

configuration/CHANGELOG.md, configuration/Cargo.toml
Needed for testing with gui (see wip PR https://github.com/nomad-xyz/nomad-app/pull/272), will update sdk related packages as well
=> release: bump version number and update changelog

configuration/CHANGELOG.md, configuration/configs/development.json, configuration/configs/production.json, configuration/configs/staging.json
Are we updating this manually? Or is this coming from a script?
=> fix: hub should not have connection to itself

agents/processor/src/processor.rs, agents/watcher/src/watcher.rs, configuration/src/secrets.rs, nomad-core/src/traits/mod.rs
ran `cargo +nightly clippy --fix --all-features -Z unstable-options`
=> chore(clippy): clippy --fix

agents/watcher/src/watcher.rs
- currently, watcher only counts updates inspected for double starting at the current committed root
- the history sync syncs backwards and does not increment updates inspected for double
- PR adds small fix there
=> fix: watcher counts updates inspected from HistorySync

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml, configuration/configs/development.json
- change connext enabled to false for evmos testnet
- add missing evmos testnet connection to rinkeby
=> chore: fix development bridge gui config, bump package version and update changelog

configuration/configs/production.json
Need to release new configuration package so we can include in GUI
=> update: enable connext

configuration/CHANGELOG.md, configuration/Cargo.toml, configuration/configs/production.json
New configuration for Avalanche, reconciled with existing production configuration.
=> feat(config): avalanche in production 

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml, configuration/configs/production.json
xDai display name should say Gnosis Chain, not xDai
Update xDai display name to say Gnosis Chain, not xDai
=> chore: fix xdai display name, bump version + update changelog

configuration/CHANGELOG.md, configuration/configs/development.json, configuration/configs/staging.json
Need to deploy Neon dev to development and staging.
Ported dev/staging configs from monorepo to configuration crate.
=> feat(config): add neon dev and staging to configs

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml
Need to update configuration version
Update configuration version
=> release: bump package version and update changelog

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml, configuration/configs/development.json, configuration/configs/staging.json
Goerli should be the new hub on development + staging instead of rinkeby
Crown goerli as the new hub on development + staging instead of rinkeby
=> new hub network + release

configuration/CHANGELOG.md, configuration/configs/staging.json
Should be using staging s3 buckets in staging instead of development
Use staging s3 buckets in staging
=> hotfix: use correct staging s3 bucket

Cargo.lock, agents/kathy/CHANGELOG.md, agents/kathy/Cargo.toml, agents/processor/CHANGELOG.md, agents/processor/Cargo.toml, agents/relayer/CHANGELOG.md, agents/relayer/Cargo.toml, agents/updater/CHANGELOG.md, agents/updater/Cargo.toml, agents/watcher/CHANGELOG.md, agents/watcher/Cargo.toml
Release first version of agents.
Bump versions and changelogs.
=> chore(agents): bump agent versions to 1.0.0 for first release

chains/nomad-ethereum/src/gelato/utils.rs
Expanding Gelato deployments. BSC and Polygon unreliable.
Add forwarder proxy addresses for BSC and Polygon.
=> feat(gelato-ethereum): add proxies for bsc and polygon

configuration/CHANGELOG.md, configuration/src/gas/defaults.rs
Roll back gas hardcode for home:update calls
=> Roll back gas hardcode for home:update calls

Cargo.lock, README.md, RELEASE-TEMPLATE.md, agents/kathy/CHANGELOG.md, agents/kathy/Cargo.toml, agents/processor/CHANGELOG.md, agents/processor/Cargo.toml, agents/relayer/CHANGELOG.md, agents/relayer/Cargo.toml, agents/updater/CHANGELOG.md, agents/updater/Cargo.toml, agents/watcher/CHANGELOG.md, agents/watcher/Cargo.toml
Releasing `agents@1.1.0`.
Bump versions/changelogs for agent crates. Add release notes template for future releasors.
=> release: bump changelogs/versions for new release + add release notes template

Cargo.lock, configuration/Cargo.toml
bump config version for non-label release
=> bump: configuration version

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml, configuration/data/definitions.ts, configuration/src/bridge.rs, configuration/src/wasm/types.rs
Add accountant to evm bridge contracts struct
- [n/a] Added Tests
- [n/a] Ran PR in local/dev/staging
=> feature: add accountant to config package

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml
Prep for release of the configuration package 2.0.0
=> chore: prep for configuration release 2.0.0

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml, configuration/data/definitions.ts, configuration/data/types.rs, configuration/src/bridge.rs, configuration/src/wasm/types.rs
Add accountant deploytime info to config for deploy scripts
=> feature: accountant deploytime info in config

Cargo.lock, configuration/CHANGELOG.md, configuration/Cargo.toml
Prep for release of the configuration package 2.0.1
=> chore: prep for configuration release 2.0.1

configuration/CHANGELOG.md, configuration/src/chains/mod.rs
clean up the method and add tracing on failures
- [] Added Tests
- [n/a] Updated Documentation
=> refactor: cleaner from_env
